# Generated by Django 2.1 on 2018-09-16 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagueoffreljord', '0002_auto_20180915_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='league',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
