# Generated by Django 2.1 on 2018-09-28 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leagueoffreljord', '0003_auto_20180916_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='LolProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=48)),
                ('active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='nickname',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='league',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nickname',
        ),
        migrations.DeleteModel(
            name='Nickname',
        ),
    ]
