# Generated by Django 2.1 on 2018-10-02 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagueoffreljord', '0005_auto_20181001_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='lolprofile',
            name='league',
            field=models.CharField(default='Bronze V', max_length=48),
            preserve_default=False,
        ),
    ]
