# Generated by Django 2.1 on 2018-10-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagueoffreljord', '0006_lolprofile_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='lolprofile',
            name='division',
            field=models.CharField(default='', max_length=48),
        ),
    ]
